using System.Collections.Generic;
using System.Text;

namespace Lpc
{
    /// <summary>Per-part attribution for one imported LPC part: who made it, under which
    /// license(s), and where it came from. LPC art is CC-BY-SA / GPL / OGA-BY, so crediting
    /// the artists is mandatory.</summary>
    [System.Serializable]
    public class LpcCreditEntry
    {
        public string part;        // logical part, e.g. "torso/clothes/tunic"
        public string[] authors;
        public string[] licenses;
        public string[] urls;
        public string notes;
    }

    /// <summary>
    /// Aggregates and formats LPC attribution for the parts ACTUALLY used. The importer feeds
    /// it the credits it read from the LPC source and writes the result to CREDITS; a game can
    /// reuse the same model + <see cref="Format"/> to render an in-game attribution screen.
    /// Pure and Unity-independent (offline + EditMode tested): dedupe is case-insensitive but
    /// preserves first-seen order and original casing.
    /// </summary>
    public static class LpcCredits
    {
        public static List<string> UniqueAuthors(IEnumerable<LpcCreditEntry> entries) => Collect(entries, e => e.authors);
        public static List<string> UniqueLicenses(IEnumerable<LpcCreditEntry> entries) => Collect(entries, e => e.licenses);

        static List<string> Collect(IEnumerable<LpcCreditEntry> entries, System.Func<LpcCreditEntry, string[]> select)
        {
            var seen = new HashSet<string>(System.StringComparer.OrdinalIgnoreCase);
            var ordered = new List<string>();
            if (entries == null) return ordered;
            foreach (var e in entries)
            {
                if (e == null) continue;
                foreach (var v in Clean(select(e)))
                    if (seen.Add(v)) ordered.Add(v);
            }
            return ordered;
        }

        /// <summary>Render a complete attribution document for the given parts.</summary>
        public static string Format(IEnumerable<LpcCreditEntry> entries, string title = null)
        {
            var list = new List<LpcCreditEntry>();
            if (entries != null) foreach (var e in entries) if (e != null) list.Add(e);

            var authors = UniqueAuthors(list);
            var licenses = UniqueLicenses(list);

            var sb = new StringBuilder();
            sb.AppendLine(string.IsNullOrEmpty(title) ? "LPC ART ATTRIBUTION  (auto-generated by LPC Unity Character Creator)" : title);
            sb.AppendLine(new string('=', 70));
            sb.AppendLine("These sprites come from the Liberated Pixel Cup (LPC). You MUST credit the");
            sb.AppendLine("artists below and comply with the listed licenses (CC-BY-SA 3.0 / GPL 3.0 /");
            sb.AppendLine("OGA-BY 3.0). Generated from the parts actually imported.");
            sb.AppendLine();
            sb.AppendLine("Licenses: " + (licenses.Count > 0 ? string.Join(", ", licenses) : "(none recorded)"));
            sb.AppendLine("Authors:  " + (authors.Count > 0 ? string.Join(", ", authors) : "(none recorded)"));
            sb.AppendLine();
            sb.AppendLine("Parts (" + list.Count + "):");
            foreach (var e in list)
            {
                sb.AppendLine("  - " + (string.IsNullOrEmpty(e.part) ? "(unknown part)" : e.part));
                var a = new List<string>(Clean(e.authors));
                var l = new List<string>(Clean(e.licenses));
                var u = new List<string>(Clean(e.urls));
                if (a.Count > 0) sb.AppendLine("      authors: " + string.Join(", ", a));
                if (l.Count > 0) sb.AppendLine("      license: " + string.Join(", ", l));
                foreach (var url in u) sb.AppendLine("      url: " + url);
                if (!string.IsNullOrEmpty(e.notes)) sb.AppendLine("      notes: " + e.notes.Trim());
            }
            return sb.ToString();
        }

        static IEnumerable<string> Clean(string[] arr)
        {
            if (arr == null) yield break;
            foreach (var s in arr)
            {
                var t = s?.Trim();
                if (!string.IsNullOrEmpty(t)) yield return t;
            }
        }
    }
}
